/**
 * Global Error Codes Reference
 *
 * Centralized error codes for consistent error tracking across all API endpoints.
 * Use these codes in sendError() for standardized error logging and monitoring.
 *
 * Example usage:
 * import { ERROR_CODES } from "@/lib/errorCodes";
 * return sendError("User not found", ERROR_CODES.NOT_FOUND, 404);
 */

export const ERROR_CODES = {
  // Validation Errors (4xx)
  VALIDATION_ERROR: "VALIDATION_ERROR",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_FORMAT: "INVALID_FORMAT",
  INVALID_EMAIL: "INVALID_EMAIL",
  PASSWORD_TOO_WEAK: "PASSWORD_TOO_WEAK",

  // Authentication & Authorization Errors
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  // Resource Errors
  NOT_FOUND: "NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  EMAIL_ALREADY_IN_USE: "EMAIL_ALREADY_IN_USE",

  // Database Errors
  DATABASE_ERROR: "DATABASE_ERROR",
  DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
  QUERY_EXECUTION_FAILED: "QUERY_EXECUTION_FAILED",
  UNIQUE_CONSTRAINT_VIOLATION: "UNIQUE_CONSTRAINT_VIOLATION",

  // User-Related Errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_CREATION_FAILED: "USER_CREATION_FAILED",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
  USER_DELETION_FAILED: "USER_DELETION_FAILED",
  USER_FETCH_ERROR: "USER_FETCH_ERROR",

  // Project-Related Errors
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_CREATION_FAILED: "PROJECT_CREATION_FAILED",
  PROJECT_UPDATE_FAILED: "PROJECT_UPDATE_FAILED",
  PROJECT_DELETION_FAILED: "PROJECT_DELETION_FAILED",

  // Task-Related Errors
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_CREATION_FAILED: "TASK_CREATION_FAILED",
  TASK_UPDATE_FAILED: "TASK_UPDATE_FAILED",
  TASK_DELETION_FAILED: "TASK_DELETION_FAILED",

  // Booking-Related Errors
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  BOOKING_CREATION_FAILED: "BOOKING_CREATION_FAILED",
  BOOKING_UPDATE_FAILED: "BOOKING_UPDATE_FAILED",
  BOOKING_CANCELLATION_FAILED: "BOOKING_CANCELLATION_FAILED",
  BOOKING_CONFLICT: "BOOKING_CONFLICT",

  // Review-Related Errors
  REVIEW_NOT_FOUND: "REVIEW_NOT_FOUND",
  REVIEW_CREATION_FAILED: "REVIEW_CREATION_FAILED",
  REVIEW_UPDATE_FAILED: "REVIEW_UPDATE_FAILED",
  REVIEW_DELETION_FAILED: "REVIEW_DELETION_FAILED",

  // Payment-Related Errors
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_PROCESSING_ERROR: "PAYMENT_PROCESSING_ERROR",
  INVALID_PAYMENT_METHOD: "INVALID_PAYMENT_METHOD",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",

  // Refund-Related Errors
  REFUND_NOT_FOUND: "REFUND_NOT_FOUND",
  REFUND_FAILED: "REFUND_FAILED",
  REFUND_PROCESSING_ERROR: "REFUND_PROCESSING_ERROR",
  REFUND_ELIGIBILITY_FAILED: "REFUND_ELIGIBILITY_FAILED",

  // Server Errors (5xx)
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
};

/**
 * HTTP Status Codes for Reference
 * Use with ERROR_CODES for consistent error responses
 */
export const HTTP_STATUS_CODES = {
  // Success
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,

  // Client Errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,

  // Server Errors
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
};
